services:
  db:
    image: 'circletree/fyp-db-fyzr:12-17-2021'
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '18888:22'
      - '28888:5432'
    volumes:
      - /data/FYZR/FYP/db:/var/lib/postgresql/data
    container_name: pytorch-fyp-db-fyzr

  ml:
    image: 'circletree/fyp-ml-fyzr:03-18-2022'
    tty: true
    stdin_open: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=Asia/Shanghai
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
              driver: 'nvidia'
        limits:
          memory: 106G
    container_name: pytorch-fyp-ml-fyzr
    build:
      context: .
      shm_size: '128gb'
    volumes:
      - /data/FYZR/FYP/codespace/FYP/codespace:/workspace/FYP/codespace
    ports:
      - '8888:22'
    depends_on:
      - db
