from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, Integer, String, CHAR, Float, Date, Numeric

Base = declarative_base()
engine = create_engine('postgresql://postgres:postgres@db', echo=True, future=True)


class Month_Performance_Data(Base):
    __tablename__ = 'monthly_performance_data'

    loan_sequence_number = Column(String(12), primary_key=True)
    monthly_reporting_period = Column(Numeric(6), primary_key=True)
    current_actual_UPB = Column(Numeric(12))
    current_loan_delinquency_status = Column(String(3))
    loan_age = Column(Numeric(3))
    remaining_months_to_legal_maturity = Column(Numeric(3))
    repurchase_flag = Column(String(1))
    modification_flag = Column(String(1))
    zero_balance_code = Column(Numeric(2))
    zero_balance_effective_date = Column(Numeric(6))
    current_interest_rate = Column(Numeric(8))
    current_deferred_UPB = Column(Numeric(12))
    ddlpi = Column(Numeric(6))
    mi_recoveries = Column(Numeric(12))
    net_sales_proceeds = Column(String(14))
    non_mi_recoveries = Column(Numeric(12))
    expenses = Column(Numeric(12))
    legal_costs = Column(Numeric(12))
    maintenance_and_preservation_costs = Column(Numeric(12))
    taxes_and_insurance = Column(Numeric(12))
    miscellaneous_expenses = Column(Numeric(12))
    actual_loss_calculation = Column(Numeric(12))
    modification_cost = Column(Numeric(12))
    step_modification_flag = Column(String(1))
    deferred_payment_plan = Column(String(1))
    eltv = Column(Numeric(4))
    zero_balance_removal_ups = Column(Numeric(12))
    delinquent_accrued_interest = Column(Numeric(12))
    delinquency_due_to_disaster = Column(String(1))
    borrower_assistance_status_code = Column(String(1))
    year = Column(Numeric(4))
    quarter = Column(Numeric(1))



class Month_Performance_Data_Sample(Base):
    __tablename__ = 'monthly_performance_data_sample'

    loan_sequence_number = Column(String(12), primary_key=True)
    monthly_reporting_period = Column(Numeric(6), primary_key=True)
    current_actual_UPB = Column(Numeric(12))
    current_loan_delinquency_status = Column(String(3))
    loan_age = Column(Numeric(3))
    remaining_months_to_legal_maturity = Column(Numeric(3))
    repurchase_flag = Column(String(1))
    modification_flag = Column(String(1))
    zero_balance_code = Column(Numeric(2))
    zero_balance_effective_date = Column(Numeric(6))
    current_interest_rate = Column(Numeric(8))
    current_deferred_UPB = Column(Numeric(12))
    ddlpi = Column(Numeric(6))
    mi_recoveries = Column(Numeric(12))
    net_sales_proceeds = Column(String(14))
    non_mi_recoveries = Column(Numeric(12))
    expenses = Column(Numeric(12))
    legal_costs = Column(Numeric(12))
    maintenance_and_preservation_costs = Column(Numeric(12))
    taxes_and_insurance = Column(Numeric(12))
    miscellaneous_expenses = Column(Numeric(12))
    actual_loss_calculation = Column(Numeric(12))
    modification_cost = Column(Numeric(12))
    step_modification_flag = Column(String(1))
    deferred_payment_plan = Column(String(1))
    eltv = Column(Numeric(4))
    zero_balance_removal_ups = Column(Numeric(12))
    delinquent_accrued_interest = Column(Numeric(12))
    delinquency_due_to_disaster = Column(String(1))
    borrower_assistance_status_code = Column(String(1))
    year = Column(Numeric(4))
